WL-12 tabs + storybook
Incubator-internship/frontend pull request #11
Opened 2024-10-23 15:05 UTC by ArtemRubtsov

Added: 
- Tabs Component
- Storybook story 
- SCSS styles

2024-10-23 15:30 UTC, kalibria approved these changes

2024-10-23 16:54 UTC, ArtemRubtsov commented
Added to storybbok/preview.ts color Light

2024-10-24 10:09 UTC, dzlek submitted a review, later dismissed

2024-10-24 11:19 UTC, dzlek requested changes
нужно сделать стиль из фигмы
![image](https://github.com/user-attachments/assets/9960d6e5-0072-4fdc-89dc-05bfc128cfa1)

2024-10-24 12:57 UTC, ArtemRubtsov commented
Переделаю. Я через вкладку до переходил, а там дизайн карточек 🤬

2024-10-25 19:42 UTC, ArtemRubtsov reviewed
fixing styles from figma

2024-10-26 07:27 UTC, m-diana-dev reviewed
![2024-10-26_10-25-57](https://github.com/user-attachments/assets/9904de8e-af6d-4746-b8e5-edc5b3cc421e)
Stylelint отвалился

2024-10-26 09:30 UTC, ArtemRubtsov commented
Настроил stylelint

2024-10-26 09:40 UTC, m-diana-dev approved these changes

2024-10-26 09:51 UTC, dzlek approved these changes

2024-10-26 10:28 UTC, merged