Wl 6 card
Incubator-internship/frontend pull request #12
Opened 2024-10-23 19:40 UTC by Serhii-Ki

Created card component

2024-10-24 11:10 UTC, dzlek requested changes
в компоненте предлагаю добавить rest, думаю понадобится
export const Card = ({ children, **...rest** }: Props) => {
  return <div className={s.card} **{...rest}**>{children}</div>
}

в сторис закинь как остальные компоненты
![image](https://github.com/user-attachments/assets/f7fa58d9-2764-44e2-a133-80fcc29bb3e1)

2024-10-25 08:01 UTC, dzlek approved these changes

2024-10-25 09:52 UTC, m-diana-dev reviewed
![2024-10-25_12-47-31](https://github.com/user-attachments/assets/371e3542-2b89-4beb-839c-824864a2a25a)
Добавить _ComponentPropsWithoutRef_, чтобы передавать в rest что-то, что свойственно div. И передать таким образом _className_, чтобы этот пропс не перезатирал стили по умолчанию. И в стилях желательно добавить _flex-direction: column;_ , иначе у нас при заполнении карточки все будет в ряд, а должно в колонку

2024-10-26 07:34 UTC, m-diana-dev reviewed
![2024-10-26_10-32-24](https://github.com/user-attachments/assets/726bbb81-f97b-4e03-a33e-d7d6a2af7bf5)
Отлично) Только небольшую опечатку исправить, а то стили не применились

2024-10-26 09:46 UTC, m-diana-dev approved these changes

2024-10-26 09:47 UTC, merged