Wl 13 header
Incubator-internship/frontend pull request #29
Opened 2024-11-04 14:56 UTC by Serhii-Ki

2024-11-05 08:34 UTC, dzlek requested changes
![image](https://github.com/user-attachments/assets/3731b48d-14af-4bff-9934-ab00e5790f54)
Подчеркивает Select: или в селектпропс поправь, или вариант 'language' добавь в select , или <Select defaultValue={'1'} items={[]} variant={'narrow'} /> 
PS. вариант 1 и narrow - "узкий' звучит кхм неоднозначно, я бы называл с каким то смысловым содержанием, типа ru и вариант lang. А почему вообще narrow этот варик называется...и почему выбран не английский вариант, весь сайт то на английском. Захотел на ru - выбрал ru, а сейчас активен en, так логично.

2024-11-05 10:11 UTC, m-diana-dev commented
> ![изображение](https://private-user-images.githubusercontent.com/78316235/383052879-3731b48d-14af-4bff-9934-ab00e5790f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDEzMDcsIm5iZiI6MTczMDgwMTAwNywicGF0aCI6Ii83ODMxNjIzNS8zODMwNTI4NzktMzczMWI0OGQtMTRhZi00YmZmLTk5MzQtYWIwMGU1NzkwZjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDEwMDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiOTMzMjFjODg0OTVmNDE3YjIwMjFlZTNlYzAxMDQwMjU2NTA0MDEwODRjNWZhYTMyM2IxY2Q4OTNhY2FjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JVFvuwmHs3KcBOF1CIZv-0SfZRUbCEAh-rmPEPN9-IA) Подчеркивает Select: или в селектпропс поправь, или вариант 'language' добавить в select , или <Select defaultValue={'1'} items={[]}variant={'narrow'} /> PS. вариант 1 и узкий - "узкий" звучит как-то странно, я бы назвал это каким-то смысловым изменением, типа ru и вариант lang. А почему вообще узкий этот вариант называется... и почему выбран не английский вариант, весь сайт на английском. Захотел на ру - выбрал ру, а сейчас активен, так логично.

Ну это уже вопрос к селекту, по сути и вариант lang тоже излишний будет. Мы должны любые варианты просто принимать в items. И не обрабатывать внутри кастомного селекта эти языки, мне кажется

2024-11-05 11:22 UTC, dzlek commented
а я в этом согласен, можно и items передать туда ...проблема в отсутствии передачи и как следствие -  ошибка. В селекте item обязательный пропс, что вполне логично.

2024-11-05 17:09 UTC, dzlek approved these changes

2024-11-06 09:31 UTC, m-diana-dev approved these changes

2024-11-06 09:31 UTC, merged